### ISSUE TITLE
The plugin does not support Camunda modeler 5.12

### ISSUE THREAD

**Issue by crazyheinz** [camunda/camunda-modeler-token-simulation-plugin#63]
When I toggle token simulation on, I get this output. 

[diagram_1.bpmn] A DOM element reference is required
    at new (webpack://camunda-modeler-token-simulation-plugin/node_modules/min-dom/dist/index.esm.js:75:0)
    at classes (webpack://camunda-modeler-token-simulation-plugin/node_modules/min-dom/dist/index.esm.js:63:0)
    at file:///Users/hannes/Library/Application%20Support/camunda-modeler/resources/plugins/camunda-modeler-token-simulation-plugin/client/client.bundle.js:46:55
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/656.js:2:27386
    at listener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:33)
    at _invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:23)
    at _invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:23)
    at ToggleMode.toggleMode (webpack://camunda-modeler-token-simulation-plugin/node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:84:0)
    at HTMLDivElement.<anonymous> (webpack://camunda-modeler-token-simulation-plugin/node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:55:0)
    at apply (webpack://camunda-modeler-client/node_modules/@sentry/browser/esm/helpers.js:72:22) [ error ]
This error may be the result of a plug-in compatibility issue.

Steps to Reproduce

Install Camunda Modeller 5.12
Toggle the Token Simulation

Environment

OS: macOs Ventura 13.4
Latest version of the plug in

**Comment by nikku** [comment]
This has previously been reported via https://github.com/camunda/camunda-modeler/issues/3672 and is now fixed in the modeler, pending a modeler release.
