### ISSUE TITLE
Disabling token simulation doesn't work in Camunda Desktop Modeler v5.12.0

### ISSUE THREAD

**Issue by hkupitz** [camunda/camunda-modeler-token-simulation-plugin#64]
__Describe the Bug__

Disabling the token simulation mode in the current version of the _Camunda Desktop Modeler_ doesn't work properly, producing the following error:

```
[diagram_1.bpmn] A DOM element reference is required
    at new (webpack://camunda-modeler-token-simulation-plugin/node_modules/min-dom/dist/index.esm.js:75:0)
    at classes (webpack://camunda-modeler-token-simulation-plugin/node_modules/min-dom/dist/index.esm.js:63:0)
    at file:///D:/Camunda%20Modeler/camunda-modeler-5.12.0/plugins/camunda-modeler-token-simulation-plugin-master/client/client.bundle.js:46:55
    at file:///D:/Camunda%20Modeler/camunda-modeler-5.12.0/resources/app.asar/public/656.js:2:27386
    at listener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:33)
    at _invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:23)
    at _invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:23)
    at ToggleMode.toggleMode (webpack://camunda-modeler-token-simulation-plugin/node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:84:0)
    at HTMLDivElement.<anonymous> (webpack://camunda-modeler-token-simulation-plugin/node_modules/bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode.js:55:0) [ error ]
 ```

The token simulation mode subsequently remains enabled and functional but can only be exited by closing the BPMN diagram.

__Steps to Reproduce__

1. Install a vanilla copy of the _Camunda Desktop Modeler_ v5.12.0
2. Install the _Token Simulation Plugin_
3. Create a new BPMN diagram
4. Click on the "Token Simulation" toggle button or press T to enable the token simulation mode
5. Click on the "Token Simulation" toggle button or press T to disable the token simulation mode

__Expected Behavior__

Toggling the token simulation mode should work without any issue.

__Environment__

- OS: Windows 10
- Plugin version: [Commit 85aa974ae5877dfa4bca585c258132a429566dca](https://github.com/camunda/camunda-modeler-token-simulation-plugin/commit/85aa974ae5877dfa4bca585c258132a429566dca)
- Desktop Modeler version: 5.12.0 (x64)

**Comment by hkupitz** [comment]
Wasn't sure where to post this. If you think this is a regression bug with the latest Desktop Modeler version, feel free to move the issue there.
