### ISSUE TITLE
Migrate to supported node version (doesn't bundle with Node>16)

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler-token-simulation-plugin#65]
__What should we do?__

Migrate to supported node version (doesn't work with Node>16). This is probably related to Webpack update.

__Why should we do it?__

`Bundle` fails when using Node 18 or 20.

```
❯ npm run all

> camunda-modeler-token-simulation-plugin@0.17.0 all
> run-s bundle


> camunda-modeler-token-simulation-plugin@0.17.0 bundle
> webpack

node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/NormalModule.js:867:17)
    at handleParseResult (/Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/NormalModule.js:933:10)
    at /Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/NormalModule.js:1025:4
    at processResult (/Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/NormalModule.js:742:11)
    at /Users/maciej/workspace/bpmn-io/camunda-modeler-token-simulation-plugin/node_modules/webpack/lib/NormalModule.js:806:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.0
ERROR: "bundle" exited with 1.
```

**Comment by nikku** [comment]
Likely requires a bump to latest `webpack` version to fix.

**Comment by hkupitz** [comment]
Not sure if this is the cause but on the latest Desktop Modeler version 5.15.0, the plugin doesn't work anymore. It outputs the following error when trying to toggle it on via the menu:

> toggleTokenSimulation is not a registered action
    at a (webpack://camundanode_modules/diagram-js/lib/features/editor-actions/EditorActions.js:266:9)
    at error (webpack://camundanode_modules/diagram-js/lib/features/editor-actions/EditorActions.js:175:10)
    at trigger (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:747:40)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack://camunda-modeler-client/src/app/App.js:1881:15)
    at fn (webpack://camunda-modeler-client/src/app/App.js:2388:19)
    at file:///D:/Camunda%20Modeler/camunda-modeler-5.15.0/resources/app.asar/public/bundle.js:2:3451066
    at exec (webpack://camunda-modeler-client/src/app/AppParent.js:76:11)
    at triggerAction (webpack://camunda-modeler-client/src/app/AppParent.js:350:61) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]

**Comment by hkupitz** [comment]
You seem to be right, just tried another plugin, and it gives me the same error.
